/* ==========================================================================
   Capitals: real places that are NOT a capital (test fixture)

   2789 cities, former capitals, regional capitals, regions, islands
   and continents, in Latin and in Greek script, that a player could plausibly
   type. selftest.mjs checks that NONE of them is accepted for any country
   whose capital it is not, whether exactly or as a tolerated misspelling:
   the owner's original complaint, a wrong answer marked correct, guarded
   against the typo tolerance. When a new capital, alternative or matcher
   change lets one through, the selftest fails; add the place to DECOY_CITIES
   in index.html, or, if it really is a name of that capital, to its alt list.
   ========================================================================== */
const split = (t) => t.split(/[,\n]/).map((s) => s.trim()).filter(Boolean);
export const PLACES_LATIN = split(`
A Coruna,Aachen,Aalborg,Aarhus,Aba,Abadan,Abbottabad,Abeche,Abeokuta,Aberdeen,Abha,Abomey,Acapulco,Acre,Adama,
Adamstown,Adana,Adelaide,Aden,Adrianople,Aegina,Africa,Agadez,Agadir,Agartala,Agra,Agram,Agrigento,
Aguascalientes,Ahmedabad,Ahvaz,Aix,Aizawl,Ajaccio,Ajman,Ajmer,Akita,Akmolinsk,Akron,Aksum,Aktau,Aktobe,Akure,
Akureyri,Al Ain,Al Rayyan,Al Wakrah,Alajuela,Alanya,Alaska,Albany,Albufeira,Albuquerque,Aleppo,Alesund,
Alexandria,Algarve,Ali Sabieh,Alicante,Aligarh,Allahabad,Alma Ata,Alma-Ata,Almaty,Almeria,Alofi,Alor Setar,
Alps,Amalfi,Amaravati,Amarillo,Amazon,Ambato,Ambon,America,Amiens,Amritsar,Anaheim,Anchorage,Ancona,Andes,
Aneho,Angeles,Angers,Angkor,Angora,Annaba,Annapolis,Anse Boileau,Antakya,Antalya,Antarctica,Antioch,Antipolo,
Antofagasta,Antsirabe,Antsiranana,Antwerp,Anuradhapura,Aomori,Aosta,Aqaba,Aracaju,Arad,Arbil,Arctic,Ardabil,
Arequipa,Arezzo,Arica,Arizona,Arkhangelsk,Arles,Arlington,Arnhem,Aruba,Arusha,Asansol,Ascension,Ashdod,
Ashkhabad,Asia,Asmera,Aspen,Assab,Assisi,Assomada,Astrakhan,Asyut,Atakpame,Atar,Atlanta,Auckland,Augsburg,
Augusta,Aurangabad,Aurora,Austin,Ava,Avarua,Aveiro,Avignon,Avila,Axum,Ayacucho,Ayutthaya,Baalbek,Babylon,
Bacolod,Badajoz,Baden-Baden,Bafata,Bafoussam,Bagamoyo,Bagan,Bago,Baguio,Bahawalpur,Bahia,Bahia Blanca,
Bahir Dar,Baidoa,Bairiki,Bakau,Bakersfield,Bali,Balikpapan,Balkans,Balti,Baltic,Baltimore,Bamberg,Bamenda,
Bandar Abbas,Bandung,Banfora,Bangalore,Banja Luka,Bansko,Barcelona,Bareilly,Bari,Bariloche,Barinas,Barisal,
Barnaul,Baroda,Barquisimeto,Barranquilla,Basel,Basra,Basse-Terre,Bata,Batam,Batavia,Bath,Bathurst,Batman,Batna,
Baton Rouge,Battambang,Batumi,Bauchi,Bavaria,Bayamon,Bayreuth,Beersheba,Beira,Bejaia,Bekasi,Belem,Belfast,
Belgaum,Belgorod,Belize City,Belo Horizonte,Benares,Bender,Bengal,Bengaluru,Benghazi,Benguela,Benidorm,
Benin City,Berat,Berbera,Berberati,Bergamo,Bergen,Berkeley,Bermuda,Bertoua,Besancon,Bethlehem,Beverly Hills,
Bhaktapur,Bhopal,Bhubaneswar,Bialystok,Biarritz,Bielefeld,Bien Hoa,Bihac,Bihar,Bilbao,Bimbo,Biratnagar,
Birmingham,Biskra,Bismarck,Bitola,Bizerte,Blackpool,Blantyre,Bled,Blida,Blumenau,Bo,Boa Vista,Bobo-Dioulasso,
Bobruisk,Bochum,Bodo,Bodrum,Bogor,Bohicon,Boise,Bolgatanga,Bologna,Boma,Bombay,Bonn,Bor,Boracay,Bordeaux,
Borneo,Bosaso,Boston,Bouake,Boulder,Bournemouth,Brades,Bradford,Braga,Brasov,Braunschweig,Breda,Bregenz,Bremen,
Brescia,Breslau,Brest,Brighton,Brikama,Brindisi,Brisbane,Bristol,Brittany,Brno,Broken Hill,Bronx,Brooklyn,
Bruges,Brugge,Bryansk,Bucaramanga,Buchanan,Buda,Budva,Buea,Buffalo,Bukavu,Bukhara,Bulawayo,Bunia,Buraidah,
Burgas,Burgos,Burgundy,Bursa,Busan,Butare,Byblos,Bydgoszcz,Byzantium,Cabinda,Cabo San Lucas,Cadiz,Caen,
Caesarea,Cagayan de Oro,Cagliari,Cahul,Cairns,Cajamarca,Calabar,Calais,Calcutta,Calgary,Cali,Calicut,
California,Camaguey,Cambridge,Cambridge MA,Campinas,Campo Grande,Campobasso,Can Tho,Canakkale,Cancun,Cannes,
Canterbury,Canton,Cap-Haitien,Cape Coast,Cappadocia,Capri,Caribbean,Carson City,Cartagena,Cartago,Carthage,
Casablanca,Cascais,Castellon,Catalonia,Catania,Catanzaro,Cayenne,Cebu,Celje,Cesky Krumlov,Ceuta,Chaguanas,
Chandigarh,Chandler,Changchun,Changsha,Changwon,Charleroi,Charleston,Charlotte,Charlotte Amalie,Charlottetown,
Cheboksary,Chefchaouen,Chelyabinsk,Chemnitz,Chengdu,Chennai,Cherkasy,Chernihiv,Chernivtsi,Cheyenne,Chiang Mai,
Chiang Rai,Chiba,Chicago,Chiclayo,Chihuahua,Chillan,Chimbote,Chimoio,Chinandega,Chingola,Chita,Chittagong,
Choloma,Chongqing,Christchurch,Christiansborg,Chula Vista,Cienfuegos,Cincinnati,Cinque Terre,Ciudad Bolivar,
Ciudad del Este,Ciudad Guayana,Ciudad Juarez,Clermont-Ferrand,Cleveland,Cluj,Cobija,Cochin,Cockburn Town,
Coimbatore,Coimbra,Cologne,Colon,Colonia,Colorado Springs,Columbia,Columbus,Comayagua,Comilla,Como,Concepcion,
Concord,Congo River,Constanta,Constantine,Constantinople,Coquimbo,Cordoba,Corfu,Corinth,Cork,Corpus Christi,
Corrientes,Corsica,Cottbus,Coventry,Coxs Bazar,Cozumel,Craiova,Crete,Crimea,Ctesiphon,Cucuta,Cuenca,Cuenca ES,
Cuiaba,Culiacan,Cumana,Curacao,Curepipe,Curitiba,Cusco,Cuzco,Cyrenaica,Da Lat,Da Nang,Dacca,Daegu,Daejeon,
Dakhla,Dalian,Dallas,Daloa,Damietta,Danube,Danzig,Daraa,Darfur,Darjeeling,Darwin,Datong,Daugavpils,Davao,David,
Davos,Dayton,Debrecen,Dehradun,Deir ez-Zor,Delft,Denizli,Denpasar,Denver,Depok,Derby,Derna,Derry,Des Moines,
Dessie,Detroit,Dhahran,Dhanbad,Differdange,Dijon,Dire Dawa,Diriyah,Dispur,Diyarbakir,Djenne,Djerba,Djokjakarta,
Djougou,Dnipro,Dolisie,Donbas,Donetsk,Dongguan,Donostia,Dortmund,Dosso,Douala,Douglas,Dover,Dover UK,Drammen,
Dresden,Dubai,Dubrovnik,Duisburg,Dundee,Dunedin,Dunhuang,Dunkirk,Durango,Durban,Durham,Durres,Dusseldorf,
East London,Echmiadzin,Edinburgh,Edirne,Edmonton,Edo,Eger,Eilat,Eindhoven,El Alamein,El Alto,El Obeid,El Paso,
Elbasan,Elche,Eldoret,Elisabethville,Elsinore,Encarnacion,Ensenada,Entebbe,Enugu,Ephesus,Erbil,Erfurt,Erivan,
Erzurum,Esbjerg,Esch,Escuintla,Eskisehir,Esmeraldas,Espoo,Essaouira,Essen,Europe,Evora,Exeter,Fairbanks,
Faisalabad,Faiyum,Fallujah,Faridabad,Faro,Faroe,Fatehpur Sikri,Ferizaj,Ferrara,Fes,Fethiye,Fez,Fianarantsoa,
Fier,Flensburg,Florence,Florianopolis,Florida,Foggia,Fomboni,Fort Jameson,Fort Portal,Fort Wayne,Fort Worth,
Fort-de-France,Fort-Lamy,Fortaleza,Foshan,Foz do Iguacu,Franceville,Francistown,Frankfort,Frankfurt,
Fredericton,Freeport,Freiburg,Fremantle,Fremont,Fresno,Frunze,Fuerteventura,Fujairah,Fukuoka,Funchal,Fustat,
Fuzhou,Gaberones,Gabes,Gabu,Galapagos,Galati,Galicia,Galkayo,Galle,Galway,Gandhinagar,Gangtok,Ganja,Gao,
Garland,Garoua,Garowe,Gaza,Gaziantep,Gbarnga,Gdansk,Gdynia,Geelong,General Santos,Geneva,Genoa,George Town,
Ghardaia,Ghaziabad,Ghazni,Ghent,Gibraltar,Gijon,Girona,Gisenyi,Giza,Gjakova,Gjirokaster,Glasgow,Glendale,Goa,
Goiania,Gold Coast,Goma,Gomel,Gonaives,Gondar,Gonder,Goree,Gothenburg,Gottingen,Gozo,Gqeberha,Grahamstown,
Gran Canaria,Granada,Grand Baie,Grand-Bassam,Graz,Greenland,Greensboro,Greifswald,Grenoble,Grodno,Groningen,
Grozny,Guadalajara,Guadeloupe,Guam,Guangzhou,Guantanamo,Guarulhos,Guayaquil,Guernsey,Guilin,Guimaraes,Guiyang,
Gujarat,Gujranwala,Gulu,Gurgaon,Guwahati,Gwadar,Gwalior,Gwangju,Gwelo,Gweru,Gyeongju,Gyor,Gyumri,Ha Long,
Haarlem,Hagatna,Hai Phong,Haifa,Haikou,Hail,Hainan,Hakone,Halifax,Halle,Hama,Hamadan,Hamamatsu,Hamburg,
Hamilton,Hammamet,Hangzhou,Hannover,Hanover,Hanseong,Harar,Harbin,Hargeisa,Haridwar,Harlem,Harper,Harrisburg,
Hartford,Hat Yai,Havant,Hawaii,Hawassa,Hebron,Hefei,Heian,Heidelberg,Helena,Heliopolis,Helsingborg,Helsingor,
Henderson,Herat,Herceg Novi,Heredia,Hermosillo,Hialeah,Hilo,Hiroshima,Ho Chi Minh City,Hobart,Hodeidah,Hohhot,
Hoi An,Hokkaido,Holguin,Hollywood,Holon,Homs,Honolulu,Honshu,Houston,Howrah,Hsinking,Hua Hin,Huambo,Huancayo,
Hubli,Hue,Huelva,Hull,Hurghada,Huye,Hwange,Hyderabad,Hyderabad PK,Iasi,Ibadan,Ibague,Ibarra,Ibb,Ibiza,Ica,
Idaho,Idlib,Ife,Iloilo,Ilorin,Imphal,Incheon,Indianapolis,Indore,Ingolstadt,Inhambane,Innsbruck,Interlaken,
Inverness,Iona,Iowa,Ipoh,Ipswich,Iqaluit,Iquique,Iquitos,Irbid,Irbil,Irkutsk,Irvine,Irving,Isfahan,Ismailia,
Istanbul,Itanagar,Ithaca,Ivano-Frankivsk,Ivanovo,Izhevsk,Izmir,Jabalpur,Jackson,Jacksonville,Jaen,Jaffa,Jaffna,
Jaipur,Jaisalmer,Jalalabad,Jamestown,Jammu,Java,Jayapura,Jeddah,Jefferson City,Jeju,Jelgava,Jena,Jenin,Jerash,
Jerez,Jericho,Jersey,Jersey City,Jimma,Jinan,Jinja,Joao Pessoa,Jodhpur,Johannesburg,Johor Bahru,Joinville,
Jonkoping,Jos,Jounieh,Juarez,Jubail,Juiz de Fora,Juliaca,Juneau,Jurmala,Jyvaskyla,Kabale,Kabwe,Kaduna,
Kagoshima,Kaifeng,Kairouan,Kalamata,Kaliningrad,Kalomo,Kaluga,Kamakura,Kampot,Kananga,Kanazawa,Kandahar,Kandy,
Kankan,Kano,Kanpur,Kansas,Kansas City,Kaohsiung,Kaolack,Kara,Karachi,Karaganda,Karaj,Karakorum,Karbala,
Karlovy Vary,Karlsruhe,Kasane,Kashgar,Kashmir,Kassala,Kassel,Katowice,Katsina,Kaunas,Kawasaki,Kayes,Kayseri,
Kazan,Keflavik,Keijo,Kemerovo,Kenema,Kenitra,Kent,Kep,Kerala,Keren,Kerman,Kermanshah,Key West,Khabarovsk,
Khan Yunis,Kharkiv,Kharkov,Kherson,Khiva,Khobar,Khon Kaen,Khujand,Khulna,Kiel,Kiffa,Kigoma,Kikwit,Kilkenny,
Killarney,Kilwa,Kimberley,Kindia,Kindu,Kirkuk,Kirov,Kiruna,Kisangani,Kishinev,Kismayo,Kisumu,Kitakyushu,Kitwe,
Klagenfurt,Klaipeda,Knoxville,Kobe,Koblenz,Kochi,Koforidua,Koh Samui,Kohima,Koidu,Kokand,Kolkata,Kolonia,
Kolwezi,Königsberg,Konya,Koper,Korat,Korce,Korhogo,Koror,Kos,Kosice,Kostroma,Kota,Kota Bharu,Kota Kinabalu,
Kotor,Koudougou,Kozhikode,Kpalime,Krabi,Kragujevac,Krakow,Kraków,Krasnodar,Krasnoyarsk,Kribi,Kristiansand,
Kryvyi Rih,Kuantan,Kuching,Kufa,Kumamoto,Kumanovo,Kumasi,Kunduz,Kunming,Kuopio,Kupang,Kurdistan,Kurgan,Kursk,
Kusadasi,Kutaisi,Kwekwe,Kyoto,L'Aquila,La Ceiba,La Plata,La Romana,La Serena,La Spezia,Laayoune,Labe,Lae,
Lagos PT,Lahore,Lahti,Laibach,Lake Como,Lalibela,Lalitpur,Lambarene,Lamu,Langkawi,Lansing,Lanzarote,Lanzhou,
Laredo,Larkana,Larnaca,Las Palmas,Las Vegas,Latakia,Lausanne,Le Havre,Le Mans,Lecce,Leeds,Leh,Leicester,Leiden,
Leipzig,Lemberg,Leningrad,Leon,Leon ES,Leopoldville,Lesbos,Leuven,Levuka,Lexington,Lhasa,Liberec,Liberia CR,
Liege,Liepaja,Lijiang,Likasi,Lille,Limassol,Limbe,Limerick,Limoges,Limon,Lincoln,Linkoping,Linz,Lipetsk,Lira,
Lisburn,Little Rock,Liverpool,Livingstone,Livorno,Lleida,Lobito,Lodz,Logrono,Loja,Lombardy,Londonderry,
Londrina,Long Beach,Longyearbyen,Los Angeles,Louisville,Lourdes,Lourenco Marques,Luang Prabang,Lubango,Lubbock,
Lubeck,Lublin,Lubumbashi,Lucca,Lucerne,Lucknow,Luderitz,Ludhiana,Lugano,Luhansk,Lund,Luoyang,Luque,Luton,Lutsk,
Luxor,Luzon,Lviv,Lyon,Maastricht,Macapa,Macau,Maceio,Machakos,Machala,Madaba,Madeira,Madison,Madras,Madurai,
Mafeking,Mafeteng,Mafikeng,Magdeburg,Magnitogorsk,Mahajanga,Mahdia,Mahebourg,Maiduguri,Maine,Mainz,Majorca,
Majunga,Makassar,Makati,Makeni,Makhachkala,Makurdi,Malacca,Malaga,Malakal,Malang,Malanje,Malatya,Malibu,
Malindi,Mallorca,Malmo,Mamoudzou,Man,Manado,Manali,Manaus,Manchester,Mandalay,Mangalore,Manhattan,Manitoba,
Manizales,Mannheim,Mansoura,Manta,Manzini,Mar del Plata,Maracaibo,Maracay,Maradi,Marbella,Mardan,Maribor,
Mariehamn,Marigot,Maringa,Mariupol,Marmaris,Maroua,Marrakech,Marrakesh,Marsa Matruh,Marseille,Martinique,
Maryland,Masaka,Masaya,Mashhad,Massawa,Masvingo,Matadi,Matanzas,Mataram,Mathura,Matola,Matsuyama,Maturin,Maun,
Mawlamyine,Mayaguez,Mayotte,Mazar-i-Sharif,Mazatlan,Mbale,Mbandaka,Mbarara,Mbeya,Mbombela,Mbour,Mbuji-Mayi,
Mecca,Mechelen,Medan,Medellin,Medina,Meerut,Mekelle,Meknes,Melaka,Melbourne,Melekeok,Melilla,Memphis,Mendoza,
Mengo,Menorca,Merca,Merida,Meroe,Mersin,Merv,Mesa,Messina,Metz,Mexicali,Miami,Milan,Milton Keynes,Milwaukee,
Mindanao,Mindelo,Minneapolis,Miri,Miskolc,Misrata,Mitrovica,Mixco,Mobile,Modena,Mogilev,Moldavia,Molepolole,
Mombasa,Monastir,Montana,Montego Bay,Monteria,Monterrey,Montgomery,Montpelier,Montpellier,Montreal,Mopti,
Moradabad,Moravia,Morelia,Morogoro,Moron,Moshi,Mossamedes,Mostar,Mosul,Moundou,Mozambique Island,Mtskheta,
Mufulira,Muharraq,Mukalla,Mukden,Multan,Munich,Munster,Murcia,Murmansk,Murshidabad,Musanze,Mutare,Mutsamudu,
Mykolaiv,Mykonos,Mymensingh,Mysore,Mysuru,Mzuzu,Nabeul,Nablus,Nafplio,Nafplion,Nagasaki,Nagoya,Nagpur,Naha,
Naivasha,Najaf,Najran,Nakhon Ratchasima,Nakuru,Nalchik,Namangan,Namibe,Nampula,Namur,Nanchang,Nancy,Nanjing,
Nanking,Nanning,Nantes,Nanyuki,Napata,Napier,Naples,Nara,Narva,Nashik,Nashville,Nasiriyah,Natal,Naxos,Nazareth,
Ndola,Negombo,Neiva,Nelson,Nelspruit,Nesebar,Netanya,Neuquen,Nevada,New Haven,New Orleans,New York,Newark,
Newcastle,Newcastle upon Tyne,Newport,Ngaoundere,Ngozi,Nha Trang,Nicaea,Nice,Niigata,Nijmegen,Nikko,Niksic,
Nile,Nimes,Ningbo,Nis,Nisa,Niteroi,Nitra,Nizhny Novgorod,Nizwa,Noida,Nome,Nonthaburi,Norfolk,Normandy,
Norrkoping,Norwich,Nosy Be,Nottingham,Nouadhibou,Noumea,Nova Lisboa,Novgorod,Novi Sad,Novorossiysk,Novosibirsk,
Nuremberg,Nuuk,Nyala,Nyanza,Nzerekore,Oakland,Oaxaca,Obbia,Obuasi,Oceania,Ocho Rios,Odense,Odesa,Odessa,Ofen,
Ohio,Ohrid,Okayama,Okinawa,Oklahoma City,Olbia,Oldenburg,Olomouc,Olympia,Omaha,Omdurman,Omsk,Onitsha,Ontario,
Ooty,Oporto,Oradea,Oran,Oranjestad,Orebro,Oregon,Orenburg,Orlando,Orleans,Oruro,Oryol,Osaka,Osh,Oshakati,
Oshawa,Osijek,Osnabruck,Osorno,Ostend,Ostrava,Ouarzazate,Ouidah,Oujda,Oulu,Ouro Preto,Oviedo,Owerri,Oxford,
Oyem,Oyo,Padang,Paderborn,Padua,Pagan,Pago Pago,Pakse,Palembang,Palermo,Palm Beach,Palma,Palmas,Palmyra,
Palo Alto,Pamplona,Panaji,Pancevo,Panevezys,Papeete,Paphos,Parakou,Parana,Paraty,Parma,Parnu,Paros,Pasig,
Passau,Pasto,Patagonia,Pathein,Patna,Patras,Pattaya,Pau,Paysandu,Pecs,Peiping,Peja,Pekanbaru,Pemba,Pensacola,
Penza,Pereira,Perm,Perpignan,Persepolis,Perth,Perugia,Pescara,Peshawar,Pest,Petah Tikva,Petaling Jaya,Petra,
Petrograd,Petropolis,Petrozavodsk,Philadelphia,Philipsburg,Phoenix,Phuket,Pierre,Pietermaritzburg,
Pinar del Rio,Pinsk,Piran,Pisa,Pittsburgh,Piura,Plano,Playa del Carmen,Pleven,Ploiesti,Plovdiv,Plymouth,Plzen,
Pohang,Pointe-Noire,Poitiers,Pokhara,Polokwane,Poltava,Poltoratsk,Pompeii,Ponce,Pondicherry,Ponta Delgada,
Pontianak,Popayan,Port Elizabeth,Port Harcourt,Port Said,Port Sudan,Port-Gentil,Portland,Porto,Porto Alegre,
Porto Velho,Portofino,Portoviejo,Portsmouth,Posadas,Posen,Positano,Potenza,Potosi,Potsdam,Poznan,Prayagraj,
Presov,Pressburg,Prilep,Princeton,Prizren,Provence,Providence,Pskov,Puducherry,Puebla,Puerto Montt,
Puerto Plata,Puerto Princesa,Puerto Vallarta,Pula,Punakha,Pune,Punjab,Puno,Punta Arenas,Punta Cana,
Punta del Este,Puntarenas,Pusan,Qazvin,Qingdao,Qom,Quatre Bornes,Quebec,Quebec City,Queens,Queensland,
Queenstown,Quelimane,Queretaro,Quetta,Quetzaltenango,Quezon City,Qufu,Rabaul,Rafah,Raipur,Rajkot,Rajshahi,
Raleigh,Ramadi,Ramla,Rancagua,Ranchi,Rangoon,Rangpur,Raqqa,Ras al-Khaimah,Rasht,Ravenna,Rawalpindi,Reading,
Recife,Regensburg,Reggio Calabria,Reggio Emilia,Regina,Reims,Rennes,Reno,Resistencia,Reunion,Reykjanesbaer,
Rhodes,Ribeirao Preto,Richmond,Riffa,Rijeka,Rimini,Rio,Rio Branco,Rio de Janeiro,Riobamba,Rishikesh,
Rishon LeZion,Riverside,Rivne,Road Town,Rochester,Rosario,Rose Hill,Roskilde,Rosso,Rostock,Rostov,
Rostov-on-Don,Rotorua,Rotterdam,Rouen,Rovaniemi,Rubavu,Rufisque,Rugen,Ruhengeri,Rundu,Ruse,Rustenburg,Ryazan,
Saarbrucken,Sabha,Sacramento,Sahara,Saigon,Saint Paul,Saint Petersburg,Saint-Denis,Saint-Louis,Saipan,Saitama,
Salalah,Salamanca,Sale,Salem,Salerno,Salisbury,Salisbury UK,Salonica,Salt Lake City,Salta,Saltillo,Salto,
Salvador,Salzburg,Samara,Samarinda,Samarkand,Samarra,Samos,Samsun,San Antonio,San Cristobal,San Diego,
San Fernando,San Francisco,San Juan,San Juan AR,San Lorenzo,San Luis Potosi,San Miguel,San Miguel de Tucuman,
San Pedro Sula,San Remo,San Sebastian,San-Pedro,Sandakan,Sanliurfa,Santa Ana,Santa Ana SV,Santa Barbara,
Santa Cruz,Santa Cruz de Tenerife,Santa Fe,Santa Maria,Santa Marta,Santander,Santiago de Compostela,
Santiago de Cuba,Santiago de los Caballeros,Santo Domingo EC,Santorini,Santos,Sanya,Sao Luis,Sao Paulo,Sapporo,
Sarande,Saransk,Sarasota,Saratov,Sardinia,Sardis,Sargodha,Sarh,Sassari,Savannah,Savannakhet,Schwerin,Scotland,
Scottsdale,Seattle,Segou,Segovia,Sekondi-Takoradi,Semarang,Sendai,Sennar,Serekunda,Seremban,Setif,Setubal,
Sevastopol,Seville,Sfax,Shah Alam,Shamakhi,Shanghai,Sharjah,Sharm El Sheikh,Sheffield,Shenyang,Shenzhen,
Shijiazhuang,Shillong,Shimla,Shiraz,Shizuoka,Shkoder,Shubra,Sialkot,Siauliai,Sibenik,Siberia,Sibiu,Sicilia,
Sicily,Sidon,Siem Reap,Siena,Sihanoukville,Sikasso,Silesia,Simferopol,Simla,Sintra,Sion,Siracusa,Sirte,Sittwe,
Siwa,Skopelos,Sligo,Sliven,Smolensk,Smyrna,Sochi,Socotra,Sohar,Sokode,Sokoto,Solapur,Solo,Sonargaon,Sopron,
Sorocaba,Sorrento,Sousse,Southampton,Soweto,Spanish Town,Sparta,Split,Spokane,Springfield,Srinagar,St Gallen,
St Helier,St Johns Newfoundland,St Louis,St Peter Port,St Petersburg,Stalinabad,Stalingrad,Stanley,
Stanleyville,Stara Zagora,Stavanger,Stavropol,Stellenbosch,Stepanakert,Stettin,Stirling,Stockton,Stoke,
Strasbourg,Stuttgart,Suakin,Subotica,Suceava,Suez,Sukhothai,Sukhumi,Sukkur,Sulaymaniyah,Sumatra,Sumy,
Sunderland,Sunyani,Sur,Surabaya,Surakarta,Surat,Surat Thani,Surgut,Suwon,Suzdal,Suzhou,Sverdlovsk,Swakopmund,
Swansea,Sydney,Sylhet,Sylt,Syracuse,Szczecin,Szeged,Tabora,Tabriz,Tabuk,Tacloban,Tacna,Tacoma,Tadjoura,Taguig,
Tahiti,Tahoua,Taichung,Taif,Tainan,Taiyuan,Taiz,Takamatsu,Takoradi,Talca,Tallahassee,Tamale,Tamanrasset,
Tamatave,Tambov,Tampa,Tampere,Tampico,Tanga,Tangerang,Tangier,Tanta,Taormina,Taranto,Tarija,Tarragona,Tarsus,
Tartu,Tartus,Tasmania,Taunggyi,Tauranga,Tema,Temuco,Tenerife,Teresina,Ternopil,Tete,Tetouan,Tetovo,Texas,
Teyateyaneng,Thane,The Valley,Thebes,Thessaloniki,Thies,Thiruvananthapuram,Thonburi,Tianjin,Tiberias,Tibet,
Tiflis,Tigray,Tijuana,Tilburg,Timbuktu,Timisoara,Tirane,Tiraspol,Tiruchirappalli,Titograd,Tlemcen,Toamasina,
Tobruk,Toledo,Toliara,Toluca,Tolyatti,Tomsk,Topeka,Toronto,Torshavn,Torun,Touba,Toulon,Toulouse,Tourane,Tours,
Townsville,Trabzon,Transylvania,Trapani,Trento,Trenton,Treviso,Trier,Trieste,Trincomalee,Trinidad,Tripolitania,
Trivandrum,Tromso,Trondheim,Troy,Trujillo,Tsaritsyn,Tshikapa,Tskhinvali,Tucson,Tucuman,Tula,Tulsa,Tulum,Tunja,
Turin,Turku,Turpan,Tuscany,Tuzla,Tver,Tyre,Tyumen,Uberlandia,Udaipur,Udine,Udon Thani,Ufa,Ulan-Ude,Ulcinj,Ulm,
Ulsan,Ulyanovsk,Umea,Umtali,Uppsala,Urga,Urmia,Urumqi,Ushuaia,Usumbura,Utah,Utrecht,Uvira,Uyo,Uzhhorod,Vacoas,
Vadodara,Vagharshapat,Vaiaku,Vail,Valdivia,Valencia,Valladolid,Valledupar,Valparaiso,Van,Vancouver,Vantaa,
Varadero,Varanasi,Varna,Vasteras,Venice,Veracruz,Vermont,Verny,Verona,Vicenza,Victoria BC,Victoria Falls,Vigo,
Vijayawada,Villach,Villavicencio,Vina del Mar,Vinnytsia,Virginia Beach,Visakhapatnam,Visby,Vitebsk,Vitoria,
Vitoria-Gasteiz,Vladikavkaz,Vladimir,Vladivostok,Vlore,Volgograd,Vologda,Voronezh,Vryburg,Vung Tau,Wad Madani,
Wales,Walvis Bay,Warri,Waterford,Wau,Weimar,Whitehorse,Wichita,Wiesbaden,Willemstad,Windsor,Winnipeg,
Winterthur,Wolfsburg,Wollongong,Wolverhampton,Wrexham,Wroclaw,Wuhan,Wuppertal,Wurzburg,Wuxi,Xiamen,Xian,Xining,
Yakutsk,Yalta,Yanbu,Yangon,Yaroslavl,Yazd,Yei,Yekaterinburg,Yellowknife,Yinchuan,Yogyakarta,Yokohama,Yola,York,
Yukon,Zadar,Zagazig,Zahedan,Zahle,Zakopane,Zakynthos,Zamboanga,Zanzibar,Zapopan,Zaporizhzhia,Zaragoza,Zaria,
Zarqa,Zawiya,Zeeland,Zeila,Zenica,Zermatt,Zhengzhou,Zhytomyr,Ziguinchor,Zilina,Zinder,Zomba,Zrenjanin,Zurich,
Zwickau
`);
export const PLACES_GREEK = split(`
Άαχεν,Άβδηρα,Αβινιόν,Αγία Νάπα,Αγία Πετρούπολη,Άγιος Ευστράτιος,Άγιος Νικόλαος,Αγκόρα,Άγρα,Αγρίνιο,Αδελαΐδα,
Αδριανούπολη,Αζόρες,Άθως,Αϊβαλί,Αίγινα,Αίγιο,Αικατερινούπολη,Ακαπούλκο,Άκκα,Ακρα,Ακράγαντας,Αλάσκα,Αλεξάνδρεια,
Αλεξανδρούπολη,Αλιάκμονας,Αλικαρνασσός,Αλμάτι,Αλμυρός,Αλόννησος,Άλπεις,Αμαζόνιος,Αμαλιάδα,Αμβέρσα,Αμβούργο,
Αμερική,Αμιένη,Αμμόχωστος,Αμοργός,Αμύνταιο,Άμφισσα,Ανάφη,Άνδεις,Άνδρος,Αννόβερο,Άντεν,Αντίμπ,Αντιόχεια,
Αντίπαξοι,Αντίπαρος,Άξουμ,Άργος,Αργοστόλι,Αργυρόκαστρο,Αρεκίπα,Αριδαία,Αρναία,Αρούμπα,Αρούσα,Άρτα,Ασία,Ασουάν,
Ασπροβάλτα,Αστακός,Αστυπάλαια,Αττάλεια,Αυλώνα,Αφρική,Αχαρνές,Αχελώος,Βαβυλώνα,Βακτρία,Βαλένθια,Βαλένσια,
Βαλκάνια,Βαλπαραΐσο,Βανκούβερ,Βαρκελώνη,Βάρκιζα,Βάρνα,Βασιλεία,Βασόρα,Βατούμ,Βεγγάζη,Βενετία,Βέροια,Βερόνα,
Βερσαλλίες,Βηθλεέμ,Βιτόλια,Βόλγκογκραντ,Βόλος,Βομβάη,Βόνιτσα,Βόννη,Βόρειος Ήπειρος,Βόρνεο,Βοστώνη,Βούλα,Βρέμη,
Βρότσλαβ,Βύβλος,Βυζάντιο,Γάζα,Γάνδη,Γαύδος,Γενεύη,Γένοβα,Γένουα,Γιανγκόν,Γιαννιτσά,Γιοκοχάμα,Γιοχάνεσμπουργκ,
Γκάλγουεϊ,Γκέτεμποργκ,Γκίζα,Γκντανσκ,Γκόα,Γκόμα,Γκοντάρ,Γκουαγιακίλ,Γκουανγκτζού,Γκουανταλαχάρα,Γκρατς,
Γκρενόμπλ,Γλασκώβη,Γλυφάδα,Γουχάν,Γρανάδα,Γρεβενά,Γύθειο,Δέλβινο,Δελφοί,Δεσκάτη,Διδυμότειχο,Δούναβης,Δράμα,
Δρέσδη,Δυρράχιο,Έβρος,Έδεσσα,Έδεσσα Μεσοποταμίας,Εδιμβούργο,Εκβάτανα,Ελασσόνα,Ελευθερούπολη,Ελευσίνα,Ελούντα,
Επανομή,Επίδαυρος,Ερέτρια,Ερμούπολη,Εύβοια,Εύοσμος,Ευρώπη,Έφεσος,Ζαγορά,Ζαγόρι,Ζάκυνθος,Ζάλτσμπουργκ,Ζανζιβάρη,
Ζυρίχη,Ηγουμενίτσα,Ηράκλειο,Θάσος,Θέρμη,Θεσσαλονίκη,Θήβα,Θήβες,Θήρα,Θρακομακεδόνες,Ιάβα,Ιεράπετρα,Ιερισσός,
Ιεριχώ,Ιεροσόλυμα,Ιθάκη,Ικαρία,Ικόνιο,Ίλιον,Ίμβρος,Ιμπαντάν,Ίμπιζα,Ίνσμπρουκ,Ίντσον,Ιόππη,Ίος,Ιππώνας,Ισφαχάν,
Ιωάννινα,Καβάλα,Καζαμπλάνκα,Καζάν,Καισάρεια,Καλαί,Καλαμαριά,Καλαμάτα,Καλαμπάκα,Κάλι,Καλιφόρνια,Καλκούτα,
Καλλιθέα,Καλλίπολη,Κάλυμνος,Κανάρια,Κανκούν,Κάννες,Κάνο,Κανταχάρ,Κάντι,Καντόνα,Καντώνα,Κανωπός,Καοσιούνγκ,
Κάουνας,Καππαδοκία,Καράτσι,Καρδίτσα,Καρλσρούη,Κάρντιφ,Κάρπαθος,Καρπενήσι,Καρταχένα,Κάρυστος,Καρχηδόνα,Κάσος,
Κασσάνδρα,Καστελλόριζο,Καστοριά,Κατάνη,Κατάνια,Κατερίνη,Καύκασος,Κέα,Κέιμπριτζ,Κεμπέκ,Κεραμωτή,Κερασούντα,
Κερατσίνι,Κέρκυρα,Κερύνεια,Κεφαλονιά,Κηφισιά,Κιάτο,Κιλκίς,Κίμωλος,Κιότο,Κισούμου,Κίσσαμος,Κλουζ,Κνωσός,Κοζάνη,
Κοΐμπρα,Κολκάτα,Κολωνία,Κομοτηνή,Κόνιτσα,Κόρδοβα,Κόρινθος,Κορκ,Κορυτσά,Κορώνη,Κορωπί,Κόσιτσε,Κοτσαμπάμπα,
Κουμάσι,Κουρασάο,Κούσκο,Κουτάισι,Κράιστσερτς,Κρακοβία,Κρήτη,Κριμαία,Κρότωνας,Κυδωνίες,Κύθηρα,Κύθνος,Κύμη,
Κυπαρισσία,Κύπρος,Κυρήνη,Κωνσταντινούπολη,Κως,Λαγκαδάς,Λάγος,Λαμία,Λάρισα,Λάρνακα,Λας Βέγκας,Λάσα,Λαύριο,
Λαχόρη,Λβιβ,Λειψία,Λειψοί,Λεμεσός,Λένινγκραντ,Λέρος,Λέσβος,Λευκάδα,Λήμνος,Ληξούρι,Λιβαδειά,Λίβερπουλ,Λιέγη,Λιλ,
Λίμερικ,Λιμόζ,Λιντς,Λος Άντζελες,Λουβέν,Λουμπουμπάσι,Λούξορ,Λουτράκι,Λυών,Λωζάνη,Μαγιόρκα,Μαδέρα,Μαδράς,Μαϊάμι,
Μακάο,Μάλαγα,Μάλια,Μάλμε,Μανάους,Μανταλέι,Μάντσεστερ,Μαραθώνας,Μαρακαΐμπο,Μαρακές,Μαρκόπουλο,Μαρούσι,Μασσαλία,
Μασχάντ,Μέγαρα,Μεδίνα,Μεθώνη,Μέκκα,Μελβούρνη,Μέμφιδα,Μέμφις,Μεντεγίν,Μεντόσα,Μεσόγειος,Μεσολόγγι,Μεσσήνη,
Μετέωρα,Μέτσοβο,Μήλος,Μιλάνο,Μισράτα,Μομπάσα,Μοναστήρι,Μόναχο,Μονεμβασιά,Μονπελιέ,Μοντερέι,Μόντρεαλ,Μόρφου,
Μοσούλη,Μόσταρ,Μουμπάι,Μπαλί,Μπανγκαλόρ,Μπαντούνγκ,Μπάρι,Μπέιρα,Μπέλφαστ,Μπέργκεν,Μπέρμιγχαμ,Μπερμούδες,
Μπιλμπάο,Μπολόνια,Μπορντό,Μπουλαβάγιο,Μπουσάν,Μπουχάρα,Μπριζ,Μπρισμπέιν,Μπρίστολ,Μπρνο,Μυκήνες,Μύκονος,Μύτικας,
Μυτιλήνη,Ναγκασάκι,Ναγκόγια,Ναζαρέτ,Ναντζίνγκ,Νάντη,Νάξος,Ναξός Σικελίας,Νάουσα,Νάπολη,Ναύκρατις,Ναύπακτος,
Ναύπλιο,Ναύπλιον,Νέα Μουδανιά,Νέα Ορλεάνη,Νέα Πέραμος,Νέα Υόρκη,Νεάπολη,Νεάπολη Ιταλίας,Νείλος,Νέοι Επιβάτες,
Νέστος,Νίκαια,Νίκαια Γαλλίας,Νιουκάστλ,Νις,Νίσιβις,Νίσυρος,Νόβι Σαντ,Νοβοσιμπίρσκ,Ντα Νανγκ,Νταβάο,
Νταρ ες Σαλάμ,Ντεμπρέτσεν,Ντέρμπαν,Ντιζόν,Ντίσελντορφ,Ντιτρόιτ,Ντουάλα,Ντουμπάι,Ντουμπρόβνικ,Νυρεμβέργη,Ξάνθη,
Οδησσός,Οινούσσες,Οκινάουα,Όκλαντ,Ολυμπία,Όλυμπος,Ομντουρμάν,Οξφόρδη,Οράν,Ορεστιάδα,Ορλεάνη,Όρχους,Οσάκα,
Ουρανούπολη,Ουτρέχτη,Οχρίδα,Παλέρμο,Πάλμα,Παξοί,Πάργα,Πάρμα,Παρνασσός,Πάρος,Πατάγια,Πάτμος,Πάτρα,Πάφος,
Πειραιάς,Πενάνγκ,Περαία,Πέργαμος,Περθ,Περιστέρι,Περσέπολη,Πεσαβάρ,Πετρούπολη,Πήλιο,Πίζα,Ποκάρα,Πολύγυρος,Πόρος,
Πορτ Σάιντ,Πορτ Χάρκορτ,Πόρτο,Πόρτο Λάγος,Πουκέτ,Πουσάν,Πρέβεζα,Πρέσπες,Πρίζρεν,Προύσα,Πρωταράς,Πτολεμαΐδα,
Πυλαία,Πύλος,Πύργος,Ραβέννα,Ραιδεστός,Ρανγκούν,Ραφήνα,Ρέθυμνο,Ρεν,Ρενς,Ρεσίφε,Ρήγιο,Ρίο ντε Τζανέιρο,Ρόδος,
Ροζάριο,Ρότερνταμ,Ρουέν,Σαγκάη,Σαϊγκόν,Σαλαμάνκα,Σαλαμίνα,Σαλβαδόρ,Σαλονίκη,Σαμαρκάνδη,Σάμη,Σαμοθράκη,Σάμος,
Σαμψούντα,Σαν Ντιέγκο,Σαν Φρανσίσκο,Σαν Χουάν,Σάντα Κρουζ,Σαντορίνη,Σάο Πάολο,Σαπές,Σαπόρο,Σαραγόσα,Σαράντα,
Σαρδηνία,Σάρτζα,Σαχάρα,Σεβαστούπολη,Σεβίλλη,Σελινούντας,Σεμπού,Σεντζέν,Σέριφος,Σέρρες,Σέφιλντ,Σητεία,Σιάν,
Σιάτιστα,Σιάτλ,Σίβα,Σιβηρία,Σίδνεϊ,Σιδώνα,Σιέμ Ριπ,Σιένα,Σιθωνία,Σικάγο,Σικελία,Σίκινος,Σινώπη,Σιράζ,Σίφνος,
Σκανδιναβία,Σκιάθος,Σκόπελος,Σκύδρα,Σκύρος,Σμύρνη,Σοουέτο,Σότσι,Σούδα,Σουμάτρα,Σούνιο,Σουραμπάγια,Σούσα,Σουφλί,
Σπάρτη,Σπέτσες,Σπιναλόγκα,Σπλιτ,Στάλινγκραντ,Σταυρός,Σταυρούπολη,Στουτγάρδη,Στρασβούργο,Στρυμόνας,Σύβαρη,
Σύβοτα,Σύμη,Συρακούσες,Σύρος,Σφακιά,Τάγγερη,Ταϊτσούνγκ,Τάμπερε,Ταμπρίζ,Τάραντας,Ταρσός,Τάρτου,Ταΰγετος,
Τελ Αβίβ,Τένεδος,Τενερίφη,Τέξας,Τεργέστη,Τζέντα,Τήλος,Τήνος,Τιβέτ,Τίγγις,Τιμισοάρα,Τιμπουκτού,Τιχουάνα,Τολέδο,
Τορίνο,Τορόντο,Τουλούζη,Τουρ,Τούρκου,Τραπεζούντα,Τρίκαλα,Τρίπολη,Τσενάι,Τσιάνγκ Μάι,Τσιταγκόνγκ,Τσονγκτσίνγκ,
Τύρναβος,Τύρος,Ύδρα,Φαιστός,Φάρο,Φάρσαλα,Φεζ,Φέρες,Φιλαδέλφεια,Φιλιατρά,Φιλιππιάδα,Φιλιππούπολη,Φισκάρδο,
Φλόριντα,Φλωρεντία,Φλώρινα,Φολέγανδρος,Φούρνοι,Φρανκφούρτη,Φώκαια,Χαβάη,Χάβρη,Χαϊδελβέργη,Χαϊντεραμπάντ,Χάιφα,
Χαλάνδρι,Χαλέπι,Χάλκη,Χαλκηδόνα,Χαλκίδα,Χαλκιδική,Χανιά,Χαράρ,Χάρκοβο,Χαρμπίν,Χεβρώνα,Χεράτ,Χερσόνησος,Χιμάρα,
Χίος,Χιούστον,Χιροσίμα,Χο Τσι Μινχ,Χονγκ Κονγκ,Χουέ,Ψαρά,Ωκεανία,Ωραιόκαστρο
`);
