/* ==========================================================================
   search-v2 · tools/sync-engine.mjs
   Copy the deterministic engine into the Cloud Functions source tree.

       node lab/search-v2/tools/sync-engine.mjs           # copy
       node lab/search-v2/tools/sync-engine.mjs --check   # fail if they differ

   Firebase deploys ONLY the functions directory, so `require('../../pool.js')`
   from a Function does not survive deployment. The engine therefore has to exist
   inside it — and a hand-maintained second copy of the mapping generator is
   exactly the kind of thing that drifts and then silently serves participants a
   different set of prizes from the one the exporter joins against.

   So the copies are generated, never edited, and `--check` (run by
   tools/selftest.js and by the emulator test) fails the build the moment they
   stop matching the originals.
   ========================================================================== */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const APP = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DEST = join(APP, '_functions', 'functions', 'engine');
const FILES = ['config.js', 'pool.js', 'specs.js', 'ai.js'];
const BANNER = '/* GENERATED by tools/sync-engine.mjs from lab/search-v2/<name> — DO NOT EDIT. */\n';

const check = process.argv.includes('--check');
await mkdir(DEST, { recursive: true });

let drift = [];
for (const f of FILES) {
  const src = await readFile(join(APP, f), 'utf8');
  const want = BANNER + src;
  let have = null;
  try { have = await readFile(join(DEST, f), 'utf8'); } catch {}
  if (have === want) continue;
  if (check) { drift.push(f); continue; }
  await writeFile(join(DEST, f), want);
  console.log('  copied ' + f);
}

if (check) {
  if (drift.length) {
    console.error('ENGINE OUT OF SYNC — ' + drift.join(', ') +
      '\nRun: node lab/search-v2/tools/sync-engine.mjs');
    process.exit(1);
  }
  console.log('engine copies are identical to the originals (' + FILES.join(', ') + ')');
} else {
  console.log('engine synced into _functions/functions/engine/');
}
